name: Trigger auto deployment for containerapp azconapps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/azconapps-AutoDeployTrigger-44df7373-cbd3-4379-a447-c4b7e95bd45e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrazconapps.azurecr.io
          username: ${{ secrets.AZCONAPPS_REGISTRY_USERNAME }}
          password: ${{ secrets.AZCONAPPS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrazconapps.azurecr.io/azconapps:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZCONAPPS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n azconapps -g rg-azconapps-northeurope --server acrazconapps.azurecr.io --username  ${{ secrets.AZCONAPPS_REGISTRY_USERNAME }} --password ${{ secrets.AZCONAPPS_REGISTRY_PASSWORD }}
            az containerapp update -n azconapps -g rg-azconapps-northeurope --image acrazconapps.azurecr.io/azconapps:${{ github.sha }}
